### ISSUE TITLE
Socket not reconnecting after long backgrounding

### ISSUE THREAD

**Issue by simonmcl** [reown-com/reown-swift#53] opened 2024-11-03 09:27 UTC
**Describe the bug**
Just had this issue from WalletConnect happen again: https://github.com/WalletConnect/WalletConnectSwiftV2/issues/1393

It's not been fixed in ReOwn 1.0.5

**Comment by llbartekll** [comment] 2024-11-04 11:39
just to confirm, you are using Starscream v3, correct?

**Comment by simonmcl** [comment] 2024-11-04 11:51
@llbartekll correct. I'm still seeing the warning about the background task in the console regularly too. The whole thing might be complex to try to debug as it only seems to happen when backgrounded for a long time. In the meantime, i'd really appreciate the ability to call `reconnect` while using automatic mode. Just have it clear everything and set it backup. As a workaround I can just check for this when my tab bar appears

**Comment by llbartekll** [comment] 2024-11-04 12:08
I was able to experience something similar recently and check logs for the sample app, the problem is not with automatic socket mode but with Starscream itself. It just refuses to connect on every connection attempt, so `reconnect` method won't help in this case.

**Comment by simonmcl** [comment] 2024-11-04 12:20
@llbartekll oh interesting. I've never been able to catch it while debugging, I just assumed it was the reconnect dying. Let me know if you find any solution to it, otherwise if I find time next week i'll revisit my attempts to use the native apple sockets and drop starscream

**Comment by llbartekll** [comment] 2024-11-07 13:22
hey @simonmcl please upgrade to 1.0.7 the issue should be resolved. The problem was that the client was trying to reconnect to the relay with expired authentication token. 
closing the issue.

**Closed by llbartekll** 2024-11-07 13:22 UTC
Labels: bug
